/**
 * Pre-compiles the protocol JSON-Schema validators to a standalone ESM module.
 * The packaged renderer runs under CSP `default-src 'self'` (no unsafe-eval),
 * so Ajv's runtime `new Function()` compilation is not allowed there.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { Ajv2020 } from 'ajv/dist/2020.js';
import standaloneModule from 'ajv/dist/standalone/index.js';

type StandaloneFn = (ajv: Ajv2020, refs: Record<string, string>) => string;
// ajv/dist/standalone is CJS — under NodeNext the callable lives on .default at type
// level, while tsx may surface it directly; resolve whichever shape we got.
const standaloneCode: StandaloneFn = (
  typeof standaloneModule === 'function' ? standaloneModule : standaloneModule.default
) as unknown as StandaloneFn;

const schemaDir = join(import.meta.dirname, '../../../docs/protocol/schema');
const load = (name: string): object =>
  JSON.parse(readFileSync(join(schemaDir, `${name}.schema.json`), 'utf8')) as object;

const ajv = new Ajv2020({ allErrors: true, strict: false, code: { source: true, esm: true } });
for (const name of ['data-ref', 'target-ref', 'canvas-tree', 'handshake', 'sentinels', 'surface-events']) {
  ajv.addSchema(load(name));
}

let code = standaloneCode(ajv, {
  validateTree: 'https://omadia.ai/protocol/1.0/canvas-tree.schema.json',
  validateSurfaceEvent: 'https://omadia.ai/protocol/1.0/surface-events.schema.json',
});

// Ajv emits ESM exports but still pulls runtime helpers via require() —
// rewrite them to imports so the bundle stays pure ESM (ajv-validator/ajv#2209).
const helpers = new Set<string>();
code = code.replace(
  /require\("ajv\/dist\/runtime\/([a-zA-Z0-9_-]+)"\)\.default/g,
  (_match, name: string) => {
    helpers.add(name);
    return `__ajv_${name.replace(/-/g, '_')}`;
  },
);
if (/require\(/.test(code)) {
  throw new Error('unhandled require() left in generated validator code');
}
const importLines = [...helpers]
  .map((name) => `import __ajv_${name.replace(/-/g, '_')} from 'ajv/dist/runtime/${name}.js';`)
  .join('\n');

const outFile = join(import.meta.dirname, '../../src/renderer/src/validate/validators.generated.mjs');
writeFileSync(
  outFile,
  `/* eslint-disable */\n// GENERATED by tools/gen-validator/genValidator.ts — do not edit.\n${importLines}\n${code}`,
  'utf8',
);
console.log(`wrote ${outFile} (${helpers.size} runtime helper import(s))`);
