/**
 * Pre-compiles the protocol JSON-Schema validators to a standalone ESM module.
 * The packaged renderer runs under CSP `default-src 'self'` (no unsafe-eval),
 * so Ajv's runtime `new Function()` compilation is not allowed there.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { Ajv2020 } from 'ajv/dist/2020.js';
import standaloneModule from 'ajv/dist/standalone/index.js';

type StandaloneFn = (ajv: Ajv2020, refs: Record<string, string>) => string;
// ajv/dist/standalone is CJS — under NodeNext the callable lives on .default at type
// level, while tsx may surface it directly; resolve whichever shape we got.
const standaloneCode: StandaloneFn = (
  typeof standaloneModule === 'function' ? standaloneModule : standaloneModule.default
) as unknown as StandaloneFn;

const schemaDir = join(import.meta.dirname, '../../../docs/protocol/schema');
const outFile = join(import.meta.dirname, '../../src/renderer/src/validate/validators.generated.mjs');
const schemaOptional = process.env.OMADIA_SCHEMA_OPTIONAL === '1';
const committedValidatorExists = existsSync(outFile);
const schemaFiles: string[] = schemaOptional && committedValidatorExists && existsSync(schemaDir)
  ? readdirSync(schemaDir).filter((name: string) => name.endsWith('.schema.json'))
  : [];
if (schemaOptional && committedValidatorExists && schemaFiles.length === 0) {
  console.warn(
    `gen-validator: schema regeneration skipped — using committed validator at ${outFile}`,
  );
  process.exit(0);
}
const load = (name: string): object =>
  JSON.parse(readFileSync(join(schemaDir, `${name}.schema.json`), 'utf8')) as object;

const ajv = new Ajv2020({ allErrors: true, strict: false, code: { source: true, esm: true } });
for (const name of [
  'data-ref', 'target-ref', 'canvas-tree', 'handshake', 'sentinels', 'surface-events',
  // omadia-canvas-protocol/1.1 — Lumens (Live Interactivity), additive.
  'lx-ast', 'scene', 'ports-wires', 'capability-manifest', 'lumen',
]) {
  const schema = load(name) as { $defs?: { primitive?: { oneOf: { $ref: string }[] } } };
  // omadia-canvas-protocol/1.1: extend the canvas-tree `primitive` oneOf with
  // `scene` and `lumen` IN PLACE (keeping the 1.0 $id). Additive — every 1.0
  // tree still validates. Crucially, doing it under the SAME id means BOTH
  // `validateTree` AND `validateSurfaceEvent` (whose surface_snapshot refs
  // `tree` → 1.0 canvas-tree) accept a Lumen-bearing tree; a separate 1.1 id
  // would only fix validateTree and the envelope path would still reject it.
  if (name === 'canvas-tree' && schema.$defs?.primitive) {
    schema.$defs.primitive.oneOf.push(
      { $ref: 'https://omadia.ai/protocol/1.1/scene.schema.json' },
      { $ref: 'https://omadia.ai/protocol/1.1/lumen.schema.json' },
    );
  }
  ajv.addSchema(schema);
}

let code = standaloneCode(ajv, {
  validateTree: 'https://omadia.ai/protocol/1.0/canvas-tree.schema.json',
  validateSurfaceEvent: 'https://omadia.ai/protocol/1.0/surface-events.schema.json',
  // 1.1 — the Lumen whitelist parsers (structural; the L1 interpreter adds semantics).
  validateLumen: 'https://omadia.ai/protocol/1.1/lumen.schema.json',
  validateScene: 'https://omadia.ai/protocol/1.1/scene.schema.json',
  validateLxNode: 'https://omadia.ai/protocol/1.1/lx-ast.schema.json',
});

// Ajv emits ESM exports but still pulls runtime helpers via require() —
// rewrite them to imports so the bundle stays pure ESM (ajv-validator/ajv#2209).
const helpers = new Set<string>();
code = code.replace(
  /require\("ajv\/dist\/runtime\/([a-zA-Z0-9_-]+)"\)\.default/g,
  (_match, name: string) => {
    helpers.add(name);
    return `__ajv_${name.replace(/-/g, '_')}`;
  },
);
if (/require\(/.test(code)) {
  throw new Error('unhandled require() left in generated validator code');
}
const importLines = [...helpers]
  .map((name) => `import __ajv_${name.replace(/-/g, '_')} from 'ajv/dist/runtime/${name}.js';`)
  .join('\n');

writeFileSync(
  outFile,
  `/* eslint-disable */\n// GENERATED by tools/gen-validator/genValidator.ts — do not edit.\n${importLines}\n${code}`,
  'utf8',
);
console.log(`wrote ${outFile} (${helpers.size} runtime helper import(s))`);
