import { defineConfig } from 'vitepress';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Version dropdown entries are generated by scripts/generate.mjs (run in the
// prebuild hook). Fall back to a single "latest" entry if it hasn't run yet so
// `vitepress` never crashes on a cold checkout.
let versions: { text: string; link: string }[] = [{ text: 'Latest', link: '/latest/' }];
try {
  versions = JSON.parse(
    readFileSync(new URL('./versions.json', import.meta.url), 'utf8'),
  );
} catch {
  /* generator not run yet — keep the fallback */
}

// Project Pages live under /omadia-ui/. Override with DOCS_BASE=/ for a custom
// domain (e.g. a CNAME to omadia.ai).
const base = process.env.DOCS_BASE ?? '/omadia-ui/';

export default defineConfig({
  base,
  lang: 'en-US',
  title: 'Omadia UI — Lume Visual Spec',
  description:
    'The Lume visual specification for Omadia UI — light-as-material design system, '
    + 'design tokens, primitives, and composition idioms. Versioned and authored.',
  cleanUrls: true,
  lastUpdated: true,
  ignoreDeadLinks: true,
  head: [
    ['meta', { name: 'theme-color', content: '#0b6b6b' }],
    ['meta', { property: 'og:title', content: 'Omadia UI — Lume Visual Spec' }],
    ['meta', { property: 'og:type', content: 'website' }],
  ],
  themeConfig: {
    nav: [
      { text: 'Latest spec', link: '/latest/', activeMatch: '^/latest/' },
      { text: 'Versions', items: versions },
      { text: 'History', link: '/history' },
      { text: 'GitHub', link: 'https://github.com/byte5ai/omadia-ui' },
    ],
    sidebar: [
      {
        text: 'Lume Visual Spec',
        items: [
          { text: 'Latest (v0.4)', link: '/latest/' },
          { text: 'Version history & authorship', link: '/history' },
        ],
      },
      {
        text: 'Browse versions',
        collapsed: false,
        items: versions,
      },
    ],
    outline: { level: [2, 3], label: 'On this page' },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/byte5ai/omadia-ui' },
    ],
    search: { provider: 'local' },
    editLink: {
      pattern: 'https://github.com/byte5ai/omadia-ui/edit/main/docs/visual-spec.md',
      text: 'Edit the source spec on GitHub',
    },
    lastUpdatedText: 'Spec last updated',
    footer: {
      message: 'Lume Visual Specification · reconstructed from git history',
      copyright: 'Omadia UI · byte5',
    },
  },
});
